version: '3.8'
services:
  node:
    build: 
      context: .
      dockerfile: ./dockerfiles/node.dockerfile
    volumes:
      - ./src:/app
    tty: true
    stdin_open: true
    depends_on:
      - db

  dev-server:
    build: 
      context: ./src
      dockerfile: dev.dockerfile
    volumes:
      - /app/node_modules
      - ./src:/app/
    tty: true
    stdin_open: true
    depends_on:
      - db
  
  db:
    image: postgres:14.1-alpine
    env_file:
      - ./env/postgres.env
    volumes:
      - db:/var/lib/postgresql/data
    #for access during dev
    ports:
      - "5432:5432"
volumes:
  db: